; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_40khz, esp32_60khz, xiao_esp32c6_40khz_matter, xiao_esp32c6_60khz_matter

[env:esp32_40khz] ; 東日本(福島局)用
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_flags =
         -DWAKEUP_SCHEDULE="HOUR_MIN(2, 0), HOUR_MIN(6, 0), HOUR_MIN(14, 0)"
         -DLED_BUILTIN=2 ; 一般的なDevKitなどは2番
lib_deps =
	 paulstoffregen/Time@^1.6

[env:esp32_60khz] ; 西日本(九州局)用
extends = env:esp32_40khz
build_flags = -DJJY_FREQ=60000

; =========================================
; ここから下が XIAO ESP32C6 & Matter用の追加分
; =========================================
[env:xiao_esp32c6_40khz_matter]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.partitions = huge_app.csv ; Matterは容量を食うのでパーティションを広げる
build_flags =
         -DWAKEUP_SCHEDULE="HOUR_MIN(2, 0), HOUR_MIN(6, 0), HOUR_MIN(14, 0)"
         -DUSE_MATTER ; main.cpp の Matterコードを有効化するスイッチ
         -DTIMEPIN=17
         -DARDUINO_USB_MODE=1 ; XIAOのUSB-C端子にSerialを出力する
         -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
         paulstoffregen/Time@^1.6

[env:xiao_esp32c6_60khz_matter]
extends = env:xiao_esp32c6_40khz_matter
build_flags = -DJJY_FREQ=60000
